### ISSUE TITLE
Sonar Azure devops extension setting -- project variable

### ISSUE THREAD

**Issue by Fazzani** [Fazzani/az-devops-extensions#11]
```yaml
- script: |
    curl --request POST -u $SONARTOKEN: \
      --data "component=$(Build.Repository.Name)" \
      --data "key=sonar.pullrequest.provider" \
      --data "value=Azure DevOps Services" \
      https://sonarcloud.io/api/settings/set
  displayName: 'Set PR provider for current project in sonarcloud'
  env:
    SONARTOKEN: $(sonar.token)
- script: |
    curl --request POST -u $SONARTOKEN: \
      --data "component=$(Build.Repository.Name)" \
      --data "key=sonar.pullrequest.vsts.token.secured" \
      --data "value=$SYSTEM_ACCESSTOKEN" \
      https://sonarcloud.io/api/settings/set
  displayName: 'Set PR token for current project in sonarcloud'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    SONARTOKEN: $(sonar.token)
```
